package com.example.qydyr.model.enums;

public enum Category {

    PARKS, DATES, HIKING, ENTERTAINMENT, EVENTS, PHOTO_SESSION, ATTRACTIONS,
    CONCERT_HALL, THEATER_HALL, STADIUM, EXHIBITION_CENTER, CONFERENCE_HALL, PARK, CINEMA
}
